Update requirements.txt
Changed from MarkupSafe==1.0 to MarkupSafe==1.1.1 to fix "ImportError: cannot import name Feature"
See https://github.com/pallets/markupsafe/issues/57